### ISSUE TITLE
The question regarding message acknowledgment. 

### ISSUE THREAD

**Issue by makasim** [sroze/enqueue-bridge#1]
The message could be acknowledged, rejected or re-queued. It should be controlled by a handler. I saw that a handler can return something. 

* Could it be such a status? 
* Is there a way to pass it back to a receiver? 
* [Rejecting messages on exception](https://github.com/sroze/enqueue-bridge/blob/master/EnqueueReceiver.php#L69) is not something we should force

**Comment by sroze** [comment]
I can see two ways of handling such thing:

1. **Using exceptions:** we could provide a couple of interfaces: `MessageToBeRejectedExceptionInterface` and `MessageToBeRequeuedExceptionInterface`. Depending on the interface implemented by the thrown exception, we would either reject or re-queue.

2. **Using a voter:** when an exception happens, we would ask a `MessageErrorHandlingVoterInterface::vote(\Throwable $exception) : int` to vote between three values like the security voters. We would therefore be able to know if we need to reject, requeue or even acknowledge.

WDYT?

**Comment by makasim** [comment]
It is not about the case where an exception has been thrown. A user might want to reject a message if it does not pass some kind of validation.

**Comment by sroze** [comment]
So it would throw an exception if the message is not valid :)

**Comment by makasim** [comment]
The consumer that received a message is responsible for its acknowledgment or rejection. But it is only available inside the receiver. 

The receiver yields message to the outside and there is no way to get some data\status back into it.

**Comment by makasim** [comment]
0.0016 to 0.035 (at that time interop queue did queue declare on every send)

**Comment by makasim** [comment]
and most of the time you do send messages from a process that serves http request where the time is very valuable resources.

**Comment by sroze** [comment]
There is [a way back with generators](http://php.net/manual/en/generator.throw.php). Such logic could be put within the Symfony Message `Worker` class, and that's it :)

```php
<?php

function receive() : \Generator
{
    $i = 0;

    while (true) {
        try {
            yield $i;
        } catch (\Throwable $e) {
            echo "Received (for $i): {$e->getMessage()}\n";

            break;
        }

        $i++;
    }
}

$generator = receive();
foreach ($generator as $integer) {
    if ($integer == 10) {
        $generator->throw(new \InvalidArgumentException('10 is not a valid number'));
    }
}

// OUTPUT:
// Received (for 10): 10 is not a valid number
```

**Comment by makasim** [comment]
what if we do this in worker:

```php
<?php
public function run()
{
    $messages = $this->receiver->receive();
    foreach ($this->receiver->receive() as $message) {
        if (!$message instanceof ReceivedMessage) {
            $message = new ReceivedMessage($message);
        }
 
        try {
            $result = $this->bus->dispatch($message);
            $messages->send($result);
        } catch (\Throwable $e) {
            $messages->throw($e);
        }
    }
}
```

and in a receiver:

```php
<?php
    public function receive(): \Generator
    {
        $destination = $this->amqpContext->createQueue($this->queueName);
        $consumer = $this->amqpContext->createConsumer($destination);

        while (true) {
            if (null === ($amqpMessage = $consumer->receive(60))) {
                continue;
            }

            try {
                $result = (yield $this->messageDecoder->decode([
                    'body' => $amqpMessage->getBody(),
                    'headers' => $amqpMessage->getHeaders(),
                    'properties' => $amqpMessage->getProperties(),
                ]));

                // use result to ack, reject, requue
            } catch (\Exception $e) {
                $consumer->reject($amqpMessage);
            }
        }
    }
```

**Comment by sroze** [comment]
Technically speaking, sending back a result would work as well. But rejecting and/or requeueing are IMHO operations that represents some failure and therefore should be represented by exceptions. Therefore, in the receiver it would look something like that:
```php
try {
    yield $this->messageDecoder->decode([
        'body' => $amqpMessage->getBody(),
        'headers' => $amqpMessage->getHeaders(),
        'properties' => $amqpMessage->getProperties(),
    ]));
     $consumer->ack($amqpMessage);
} catch (MessageToBeRequeuedExceptionInterface $e) {
    $consumer->requeue($amqpMessage);
} catch (\Exception $e) {
    // By default we reject, I guess?
    $consumer->reject($amqpMessage);
}
```

**Comment by makasim** [comment]
Wouldnt such exception be a bit low level? What should a no-MQ receiver (http one for example) do in case of such an exception

**Comment by sroze** [comment]
Well, this exception would be brought to the developers by this bridge, not the Message component directly. As they would have installed this package, they know they are using enqueue.

But you are still right, maybe these names would be better:
- `MessageShouldBeRetriedExceptionInterface`
- `MessageToBeRejectedExceptionInterface`

**Comment by makasim** [comment]
> Well, this exception would be brought to the developers by this bridge, not the Message component directly. As they would have installed this package, they know they are using enqueue.

It ties handlers to the concrete adapter implementations. It bits the main idea of the message compoent: handlers should not be coupled with adapters.

**Comment by sroze** [comment]
Both options (exceptions or return values) would couple the handlers with the adapters from the point you want the adapter to do something special for you (i.e. ack/requeue/reject). As a developers, the adapters would do something by default (in this case rejecting the message if an exception happens) but you are able to control what they do by using one of these [two options](https://github.com/sroze/enqueue-bridge/issues/1#issuecomment-357679584) (we need to chose just one) :)

**Comment by makasim** [comment]
Correct me if I am wrong. This line wouldn't be called ever.  https://github.com/sroze/enqueue-bridge/blob/master/EnqueueReceiver.php#L67
