### ISSUE TITLE
Doing queue declare on each message send drastically reduces performance. 

### ISSUE THREAD

**Issue by makasim** [sroze/enqueue-bridge#2]
Queue declaration should be rethought as the current approach has a performance penalty

https://github.com/sroze/enqueue-bridge/blob/master/EnqueueSender.php#L68

**Comment by sroze** [comment]
But it has an amazing advantage: there is no required user action, which is the expected DX. Can you suggest or PR another approach?

**Comment by makasim** [comment]
another approach is to have a separate method like `setupBroker` which could be called by a client.

Or to do it at least once (for the first method call).

**Comment by sroze** [comment]
> another approach is to have a separate method like setupBroker which could be called by a client.

That's where the DX would suffer.

> Or to do it at least once (for the first method call).

Erm... do we have an exception or something when sending to a non-existing queue/topic? Can we detect such exception, then create the queue and retry?

**Comment by Nyholm** [comment]
I think we should focus on DX but make a clear path (documentation) how it could be improved.

**Comment by makasim** [comment]
It is really big performance drop. 

https://www.dropbox.com/s/1crt1akvcjc95vf/Screenshot%202018-01-15%2015.34.42.png?dl=0


0.0016 to 0.035 (at that time interop queue driver did queue declare on every send)

and most of the time you do send messages from a process that serves HTTP request where the time is a very valuable resource.

**Comment by sroze** [comment]
Maybe this would do:

> Do we have an exception or something when sending to a non-existing queue/topic? Can we detect such exception, then create the queue and retry?

**Comment by makasim** [comment]
> Do we have an exception or something when sending to a non-existing queue/topic? Can we detect such exception, then create the queue and retry?

Let's take AMQP. It would work for sending to a topic (exchange in terms of AMQP). but as for queue there wouldn't an exception if it does not exist.

**Comment by sroze** [comment]
If by default we use topics, then it would work as a DX PoV 👍

**Comment by sroze** [comment]
Reopening as it's still a valid point. See #4 for the fix.
